enum Getters {
  PROFILE = 'getProfile',
  FRIENDS = 'getFriends',
  FOLLOWINGS = 'getFollowings',
  FOLLOWERS = 'getFollowers',
  CONTACTS = 'getContacts',
  WHEREABOUTS = 'getWhereabouts',
  NOTIFICATIONS = 'getNotifications',
  CHATS = 'getChats',
  CHAT_MESSAGES = 'getChatMessages',
  COMMENTS = 'getComments',
  POSTS = 'getPosts',
  MESSAGES = 'getMessages',
  APIS = 'getAPIs',
  CONNECTIONS = 'getConnections',
  COMMUNITIES = 'getCommunities',
  SETTINGS = 'getSettings',
  REACTED = 'getReacted',
  MEDIAS = 'getMedias',
  TRANSACTIONS = 'getTransactions',
  BROWSER_DATA = 'getBrowserData',
  TASKS = 'getTasks',
  AUTHORIZED_DEVICES = 'getAuthorizedDevices',
  MAIL = 'getMail',
}

export default Getters
